jsx-first-pro-new-line autofix implementation
idagds/eslint-plugin-react pull request #2
Opened 2016-10-01 03:57 UTC by snowypowers

First submission of autofix
- Add fixable to rules file
- Add fixers for each of the 2 cases

- Add output code for each invalid test case

2016-10-01 11:36 UTC, yangshun commented on tests/lib/rules/jsx-first-prop-new-line.js
> +        ' prop="one" />'
The indentation looks off (cross ref line 101 and line 111.

2016-10-03 02:10 UTC, snowypowers commented on tests/lib/rules/jsx-first-prop-new-line.js
> +        ' prop="one" />'
Hi I have been looking at this problem. To solve this, I would have to change the schema to intake the indent size. Would this be ok?

On a side note, jsx-indent-props solves this properly but would need a second run.

2016-10-03 04:12 UTC, snowypowers commented
Indentation has been fixed. A new test case has been added to showcase ability to specify indentation style.

2016-10-03 09:13 UTC, shioju commented on tests/lib/rules/jsx-first-prop-new-line.js
> +      output: [
Pls add test cases for tabs too. Thanks.

2016-10-03 10:34 UTC, snowypowers commented on tests/lib/rules/jsx-first-prop-new-line.js
> +      output: [
just added.

2016-10-04 05:39 UTC, shioju requested changes
Can simplify `getNodeIndent` further.

2016-10-04 05:39 UTC, shioju commented on lib/rules/jsx-first-prop-new-line.js
> +    var extraColumnStart = 0;
This is always zero. Can delete.

2016-10-04 05:39 UTC, shioju commented on lib/rules/jsx-first-prop-new-line.js
> +      var src = sourceCode.getText(node, node.loc.start.column + extraColumnStart);
`extraColumnStart` is always zero.

2016-10-04 05:39 UTC, shioju commented on lib/rules/jsx-first-prop-new-line.js
> +                  var nodeIndent = getNodeIndent(node, false, false);
`getNodeIndent`'s 2nd and 3rd arguments are default to `false`, can remove here.

2016-10-04 05:39 UTC, shioju commented on lib/rules/jsx-first-prop-new-line.js
> +      byLastLine = byLastLine || false;
`getNodeIndent` is only called in one place, and called with `byLastLine` and `excludeCommas` set to false. Can just remove these 2 variables and short circuit their values into this function to make it simpler.

2016-10-04 07:32 UTC, snowypowers commented
function amended as requested.

2016-10-04 08:30 UTC, shioju approved these changes

2016-10-04 08:35 UTC, merged

2016-10-04 08:37 UTC, shioju commented
We will contact you via email for payment matters. Pls submit a PR upstream as well, for the benefit of everyone else. Thanks. :-)

2016-10-04 09:16 UTC, shioju commented
Forgot to mention that you should also update README.md to add `(fixable)` next to this rule.

2016-11-01 01:24 UTC, revisionfour commented
Are you guys still working on this? 
[](https://github.com/yannickcr/eslint-plugin-react/pull/886 )

There are some teams across the globe that could really benefit from a --fix command for this eslint rule. Let me know if you need help. @snowypowers @shioju @yangshun @gyng @lawliet89

2016-11-01 03:08 UTC, shioju commented
yes @revisionfour, but right now it can't handle the case where the first line has more than one prop. gonna fix that then push. thanks for asking.